### ISSUE TITLE
redis is inaccessible

### ISSUE THREAD

**Issue by kyessenov** [istio/old_pilot_repo#1055]
A basic redis service appears to be inaccessible:
```
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - port: 6379
    name: tcp
    protocol: TCP
    targetPort: 6379
  selector:
    service: redis
```
