### ISSUE TITLE
Add sidecar initializer option to customize injected sidecar per deployment

### ISSUE THREAD

**Issue by ayj** [istio/old_pilot_repo#1061]
cc @costinm 

> It would be great to customize the sidecar tag (or full path) using annotations. For example to pick a debug image of sidecar for a job that needs debugging (ideally the full path of the sidecar should be specified ). Or a job may use a specialized sidecar. Or many other use cases

For example, customizing the injected sidecar image per deployment would look something like the following. The initializer would look for this annotation during injection and override the default sidecar image. The initializer may need additional policy to allow/disallow such customization to avoid undesirable proxy bypass.  

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    options.sidecar.istio.io/proxy_image: "docker.io/ayj/my_debug_proxy_image:e6ebaa8
  name: my-deployment 
# etc ... 
```
