### ISSUE TITLE
istio incorrect handle of ingress backend path

### ISSUE THREAD

**Issue by linsun** [istio/old_pilot_repo#1389]
@eigokor commented on [Wed Oct 04 2017](https://github.com/istio/issues/issues/86)

**Is this a BUG or FEATURE REQUEST?:**

**Did you review existing epics or issues to identify if this already being worked on?** (please try to add the correct labels and epics):

**Bug:**
Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
istioctl version
istioctl version:

Version: 0.1.6
GitRevision: dab2033
GitBranch: release-0.1
User: jenkins@ubuntu-16-04-build-12ac793f80be71
GolangVersion: go1.8
KubeInjectHub: docker.io/istio
KubeInjectTag: 0.1


apiserver version:

Version: 0.1.6
GitRevision: dab2033
GitBranch: release-0.1
User: jenkins@ubuntu-16-04-build-12ac793f80be71
GolangVersion: go1.8.1

kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6", GitCommit:"4bc5e7f9a6c25dc4c03d4d656f2cefd21540e28c", GitTreeState:"clean", BuildDate:"2017-09-14T06:55:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T08:56:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Is Istio Auth enabled or not ?**
Did you install istio.yaml, istio-auth.yaml....
 istio.yaml

**What happened**:
ingress rule path: /internal/v1.0/service
is handled as regex 

**What you expected to happen:**
pattern must be regex only if ".*" used

**How to reproduce it:**
https://stackoverflow.com/questions/46399248/istio-incorrect-handle-of-ingress-backend-path/46528125#46528125

**Feature Request:**
Y/N

**Describe the feature:**

**Comment by linsun** [comment]
looks like https://github.com/istio/pilot/blob/master/adapter/config/ingress/conversion.go#L158 is treating "/internal/v1.0/service" as true which caused the string to be treated as regex.

**Comment by linsun** [comment]
Looking at the code, I believe we are treating "/internal/v1.0/service" as regex.  If you look at k8s ingress spec, however it says path is supposed to be an extended POSIX regex (see link below).  Given having real dot in the path isn't very common, I'm leaning towards not do anything till further feedback from users.   cc @kyessenov @rshriram 

https://github.com/kubernetes/api/blob/master/extensions/v1beta1/types.go#L750

**Comment by rshriram** [comment]
k8s ingress uses nginx as reference implementation. Dot is very common when you use gRPC.

**Comment by eigokor** [comment]
Current implementation in istio side is not even a POSIX regex where "." matches any single character (many applications exclude newlines, and exactly which characters are considered newlines is flavor, character encoding, and platform specific, but it is safe to assume that the line feed character is included). Within POSIX bracket expressions, the dot character matches a literal dot. For example, a.c matches "abc", etc., but [a.c] matches only "a", ".", or "c".

here path  /internal/v100/service will also return 404

**Comment by frankbu** [comment]
The current implementation is using golang regex, so it's not exactly POSIX. I agree with @rshriram that literal "." characters are common, so we need to support them.

@eigokor Did you try `/internal/v1[.]0/service`?

**Comment by linsun** [comment]
i think I agree we should fix this if dot is very common with gRPC.  

We need to come down to a conclusion on how to check if it is POSIX?   One way is to do what nginx does, which they don't attempt to parse path as regex, per https://github.com/kubernetes/ingress/blob/master/controllers/nginx/pkg/template/template.go#L199

**Comment by frankbu** [comment]
See also: https://github.com/istio/istio.github.io/issues/615

Note that mapping `/*` to match `/`, `//`, `///`, etc., is also not a good implementation.

**Comment by eigokor** [comment]
> Did you try /internal/v1[.]0/service?
@frankbu yes, same result 404

**Comment by rshriram** [comment]
@eigokor can you try this: https://istio.io/docs/tasks/traffic-management/ingress.html and let me know if its of some help?

**Comment by eigokor** [comment]
@rshriram what exactly you want me to try? 

working ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simple-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - http:
      paths:
      - path: /v1/.*
        backend:
          serviceName: nginxsvcv1
          servicePort: 8000
      - path: /v2/.*
        backend:
          serviceName: nginxsvcv2
          servicePort: 8000
```

not working 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simple-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - http:
      paths:
      - path: /v1.0/
        backend:
          serviceName: nginxsvcv1
          servicePort: 8000
      - path: /v2.0/
        backend:
          serviceName: nginxsvcv2
          servicePort: 8000
```

**Comment by rshriram** [comment]
```bash
cat <<EOF | kubectl create -f -
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simple-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - http:
      paths:
      - path: /.*
        backend:
          serviceName: nginxsvcv1
          servicePort: 8000
      - path: /.*
        backend:
          serviceName: nginxsvcv2
          servicePort: 8000
EOF
```

```bash
   cat <<EOF | istioctl create -f -
   ## Deny all access from istio-ingress
   apiVersion: config.istio.io/v1alpha2
   kind: RouteRule
   metadata:
     name: deny-route
   spec:
     destination:
       name: nginxsvcv1
     match:
       # Limit this rule to istio ingress pods only
       source:
         labels:
           istio: ingress
     precedence: 1
     route:
     - weight: 100
     httpFault:
       abort:
         percent: 100
         httpStatus: 403 #Forbidden for all URLs
   EOF
```

```bash
   cat <<EOF | istioctl create -f -
   ## Allow requests to /status prefix
   apiVersion: config.istio.io/v1alpha2
   kind: RouteRule
   metadata:
     name: svcv1-route
   spec:
     destination:
       name: nginxsvcv1
     match:
       # Limit this rule to istio ingress pods only
       source:
         labels:
           istio: ingress
       request:
         headers:
           uri:
             prefix: /v1.0
     precedence: 2 #must be higher precedence than the deny-route
     route:
     - weight: 100
   EOF
```

**Comment by eigokor** [comment]
```
   cat <<EOF | istioctl create -f -
   ## Deny all access from istio-ingress
   apiVersion: config.istio.io/v1alpha2
   kind: RouteRule
   metadata:
     name: deny-route
   spec:
     destination:
       name: nginxsvcv1
     match:
       # Limit this rule to istio ingress pods only
       source:
         labels:
           istio: ingress
     precedence: 1
     route:
     - weight: 100
     httpFault:
       abort:
         percent: 100
         httpStatus: 403 #Forbidden for all URLs
   EOF
```
Error: configuration is invalid: 1 error occurred:

* name or service is mandatory for a service reference

**Comment by rshriram** [comment]
Oh shux. can you try this istio.yaml instead: https://github.com/istio/istio/blob/master/install/kubernetes/istio.yaml ?

**Comment by eigokor** [comment]
Ok, found solution.

1. had to use single service to expose both pods
```
kind: Service
apiVersion: v1
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 8000
    targetPort: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        version: v1
    spec:
      containers:
      - name: nginx
        image: nginx:1.8
        ports:
        - containerPort: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        version: v2
    spec:
      containers:
      - name: nginx
        image: nginx:1.8
        ports:
        - containerPort: 80
```

2 Ingress
```
cat <<EOF | kubectl -n istio-test apply -f -
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simple-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - http:
      paths:
      - path: /.*
        backend:
          serviceName: nginx
          servicePort: 8000
EOF
```
3. rules 

```
cat <<EOF | istioctl -n istio-test create -f -
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: nginx-v1
spec:
  destination:
    name: nginx
  precedence: 1
  route:
  - labels:
      version: v1
  match:
    request:
      headers:
        uri:
          prefix: "/v1.0/"
  rewrite:
    uri: "/"
EOF
```

```
cat <<EOF | istioctl -n istio-test create -f -
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: nginx-v2
spec:
  destination:
    name: nginx
  precedence: 1
  route:
  - labels:
      version: v2
  match:
    request:
      headers:
        uri:
          prefix: "/v2.0/"
  rewrite:
    uri: "/"
EOF
```
able to trigger
http://myELB/v1.0 
http://myELB/v1.0/
http://myELB/v2.0/

got 404 at
http://myELB/v2.0 

is it mandatory to have single service for that kind of request routing?
