### ISSUE TITLE
Redirecting all ingress http traffic to https

### ISSUE THREAD

**Issue by charlesverdad** [istio/old_pilot_repo#1512]
I am looking for a way to redirect all site visitors to the https version of my site. Something like http 301 or 302 redirect. I was told that envoy has built in support for this and we just need a way to configure that with istio.

Here's my current ingress resource for reference:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: internals-secure-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  tls:
    - secretName: istio-ingress-certs
  rules:
  - host: mysite.com
    http:
      paths:
      - path: /.*
        backend:
          serviceName: myservice
          servicePort: 80`
```
Related:
https://groups.google.com/forum/#!topic/istio-users/8SIWVX6ZSK4
